spring:
  datasource:
    url: jdbc:h2:mem:test

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      schema-locations: classpath*:db.h2/schema.sql
      data-locations: classpath*:db.h2/data.sql

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.SQL: debug

mail:
  address:
    admin: pre26@gmail.com
jwt:
  key: ${JWT_SECRET_KEY}     # GITHUB의 환경변수에서 가져오도록 수정하면 자동배포시 적용됨스
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420
