spring:
  datasource:
    url: jdbc:h2:mem:test

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      schema-locations: classpath*:db.h2/schema.sql
      data-locations: classpath*:db.h2/data.sql

logging:
  level:
    org.hibernate.SQL: debug

mail:
  address:
    admin: pre26@gmail.com
jwt:
  key: ${JWT_SECRET_KEY}     # 내컴퓨터의 환경변수에서 로드해오는 건데,, 프로젝트의 경우에는 수정이 필요 할 것 같군~
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420
